version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: car_dealership_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shrujal1766
      POSTGRES_DB: incubyte
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: car_dealership_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/incubyte
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=shrujal1766
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: car_dealership_frontend
    ports:
      - "1308:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
